ALTER TABLE "Warning" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'warning';
ALTER TABLE "Warning" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS "AdminNote" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "guildId" TEXT NOT NULL,
  "targetDiscordId" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "issuedBy" TEXT NOT NULL DEFAULT '관리자',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "AdminNote_targetDiscordId_idx" ON "AdminNote"("targetDiscordId");
CREATE INDEX IF NOT EXISTS "AdminNote_guildId_idx" ON "AdminNote"("guildId");
